name: Deploy WPG react app on AWS S3

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_PUBLIC_API_URL: ${{ vars.VITE_PUBLIC_API_URL }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS S3
        run: aws s3 sync dist ${{ vars.AWS_S3_URL }} --delete
